/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module App {
    /** Generated from Sam.Db.Models.Users.UserRole **/
    const enum UserRole {
        User = 0,
        Admin = 1,
    }
    /** Generated from Sam.Db.Models.Common.EntityObjectId<TKey> **/
    export interface EntityObjectBaseId {
        Id: any;
        CreatedDate: DateTime;
        CreatedById: string;
        JsonCreatedBy: App.User;
        ModifiedDate: DateTime;
        ModifiedById: string;
        JsonModifiedBy: App.User;
    }
    /** Generated from Sam.Db.Models.Common.EntityObjectId **/
    export interface EntityObjectId extends App.EntityObjectBaseId {
    }
    /** Generated from Sam.Db.Models.Users.JsonUser **/
    export interface User {
        Id: string;
        UserName?: string;
        Email?: string;
        UserRole: App.UserRole;
        PasswordHash?: string;
        PhoneNumber?: string;
    }
    /** Generated from Sam.Api.WebApi.MetadataApi.EntityMenu **/
    export interface EntityMenu {
        IsVisible?: boolean;
        Caption: string;
        Position?: number;
        Roles: string[];
    }
    /** Generated from Sam.Api.WebApi.MetadataApi.EntityMetadata **/
    export interface EntityMetadata {
        TableName: string;
        Url: string;
        Name: string;
        Description: string;
        RepresentExpression: string;
        KeyAttrs: string[];
        Group: string;
        Menu: App.EntityMenu;
        Properties: App.PropertyMetadata[];
        DateProperty: string;
        NumberProperty: string;
        Position: number;
    }
    /** Generated from Sam.Api.WebApi.MetadataApi.EnumerableItemMetadata **/
    export interface EnumerableItemMetadata {
        Name: string;
        Description: string;
        Value: number;
    }
    /** Generated from Sam.Api.WebApi.MetadataApi.ObjectRefMetadata **/
    export interface ObjectRefMetadata {
        Name: string;
        KeyPropertyName: string;
        ObjectPropertyName: string;
    }
    /** Generated from Sam.Api.WebApi.MetadataApi.PropertyMetadata **/
    export interface PropertyMetadata {
        ColumnName: string;
        Name: string;
        Description: string;
        Note: string;
        TypeName: string;
        EnumerableMetadata: App.EnumerableItemMetadata[];
        ObjectRefMetadata: App.ObjectRefMetadata;
        MaxLength?: number;
        MinValue?: number;
        MaxValue?: number;
        Format: string;
        Position: number;
        Required?: boolean;
        Hidden?: boolean;
        DefaultInvisible?: boolean;
    }
}
